contacts.update(
{'foo-admin': {'alias': u'foo-admin',
                    'contactgroups': ['foo-admins'],
                    'disable_notifications': False,
                    'email': 'foo-noc@techsquare.com',
                    'pager': ''},
 'foo-pager': {'alias': u'foo-pager',
                    'contactgroups': ['foo-pager'],
                    'disable_notifications': False,
                    'email': 'foo-page@techsquare.com',
                    'pager': ''},
 'foo-view': {'alias': u'foo view',
                   'contactgroups': [],
                   'disable_notifications': False,
                   'email': '',
                   'pager': ''},
 'machineuser': {'alias': u'machine',
                 'contactgroups': [],
                 'disable_notifications': False},
 'omdadmin': {'alias': u'omdadmin',
              'contactgroups': [],
              'disable_notifications': False,
              'email': '',
              'pager': ''}}
)

